### ISSUE TITLE
Problem ze znacznikami html w md

### ISSUE THREAD

**Issue by PerzotProgrammer** [inf03/inf03.github.io#2]
Niektóre znaczniki nie są wspierane w formacie md
Przykładem jest czytnik w IDE JetBrains (PhpStorm)
![image](https://github.com/user-attachments/assets/b76834ed-9146-42a1-8678-689e1b5ab8e8)
W przyszłości możliwe, że stworzę PR z poprawką

**Comment by Pawi1** [comment]
skill issue, pozdrawiam

**Comment by PerzotProgrammer** [comment]
to ty masz skill issue a nie ja
